#!/usr/bin/env ash
set -efu
repocnt=$(get -e package -e configuration -e repos -l)
cnt=0
install -o 0 -g 0 -D -m0644 static/pacman.conf /etc/pacman.conf
until [[ "$repocnt" -eq "$cnt" ]]; do
  set -- $(get -e package -e configuration -e repos \
                          -e $cnt -e name -u -p \
                          -e server -u)
  echo "[$1]" >> /etc/pacman.conf
  echo "Server = http://$2/" >> /etc/pacman.conf
  cnt=$(($cnt+1))
done
