#!/usr/bin/env ash
set -efu
installedcnt=$(get -e package -e installed -l)
cnt=0
pacman -Sy  --noprogressbar --quiet >/dev/null 2>&1
until [[ $installedcnt -eq $cnt ]]; do
  set -- $(get -e package -e installed -e $cnt -u)
  pacman -Qi $1 >/dev/null 2>&1 || pacman -S --noconfirm $1 >/dev/null 2>&1
  cnt=$(($cnt+1))
done
