#!/usr/bin/env ash
set -efu
homecnt=$(get -e permissions -e home -l)
abscnt=$(get -e permissions -e absolute -l)
cnth=0
cnta=0
until [[ $homecnt -eq $cnth ]]; do
  for users in /home/* root; do
    set -- $(get -e permissions -e home -e $cnth -k -a -u)
    chmod -f "$2" "$(grep $users /etc/passwd | cut -f6 -d:)/$1" || true
  done
  cnth=$(($cnth+1))
done
until [[ $abscnt -eq $cnta ]]; do
  set -- $(get -e permissions -e absolute -e $cnta -k -a -u)
  chmod -f "$2" "$1" || true
  cnta=$(($cnta+1))
done
