#!/usr/bin/env ash
set -efu
userscnt=$(get -e authorized_keys -e users -l)
cntu=0
until [[ $userscnt -eq $cntu ]]; do
  user=$(get -e authorized_keys -e users -e $cntu -k)
  keyscnt=$(get -e authorized_keys -e users -e $cntu -e $user -l)
  cntk=0
  rm "$(grep $user /etc/passwd | cut -f6 -d:)/.ssh/authorized_keys" 2>/dev/null || true
  mkdir "$(grep $user /etc/passwd | cut -f6 -d:)/.ssh/" 2>/dev/null || true
  chown $user:$user "$(grep $user /etc/passwd | cut -f6 -d:)/.ssh/" 2>/dev/null || true
  until [[ $keyscnt -eq $cntk ]]; do
    key=$(get -e authorized_keys -e users -e $cntu -e $user -e $cntk -u)
    echo "$(get -e authorized_keys \
         -e keys -e $key \
         -e0 -u -p \
         -e1 -u -p \
         -e2 -u | tr '\n' ' ')" >> "$(grep $user /etc/passwd | cut -f6 -d:)/.ssh/authorized_keys"
    cntk=$(($cntk+1))
  done
  chown $user:$user "$(grep $user /etc/passwd | cut -f6 -d:)/.ssh/authorized_keys"
  cntu=$(($cntu+1))
done
