#!/usr/bin/env ash
set -efu
if [[ -f static/resolv.conf ]]; then
  /usr/bin/install -o 0 -g 0 -D -m0644 static/resolv.conf /etc/resolv.conf
else
  echo -n > /etc/resolv.conf
fi
  /usr/bin/install -o 0 -g 0 -D -m0644 template/net /etc/conf.d/net
for opts in interface address netmask gateway ntpdopts; do
  sed -i "s:$opts=:$opts=$(get -e network -e configuration -e $opts -u):" /etc/conf.d/net
done
